### ISSUE TITLE
Add a package.json file to permit installation via npm ?

### ISSUE THREAD

**Issue by sdebacker** [ckeditor/ckeditor-releases#37]
What do you think about this idea ?

**Comment by Reinmar** [comment]
Why not actually. For some reason we didn't like the idea to publish releases on NPM, but since we have the `standard-all` preset available now, perhaps we can do this.

/cc @fredck @wwalc

**Comment by wwalc** [comment]
IIRC we went ahead with Bower instead of npm as it seemed more natural for website dependencies. I'm fine with publishing releases on npm as well, especially knowing that some users are missing it :) Thanks for the suggestion!

**Comment by Yannik** [comment]
It is the right time to move on to npm.

After [this](http://bower.io/blog/2015/bower-alive-looking-contributors/) blogpost:
>@desandro
    2015-11-19 19:01 UTC
    @tomdale I hear you. But a noble death still requires people to manage a funeral

>@desandro
    2015-11-19 19:03 UTC
    @tomdale We're realistic — moving to npm is right thing to do. I want to get to a state where that's an easy transition

The developer community seems to agree: https://www.reddit.com/r/webdev/comments/3tfvl2/bower_is_alive_looking_for_contributors/

So, please, even if still supporting bower, npm is the defacto standard for front end dependencies nowadays and ckeditor is one of the few projects that's not on it!

**Comment by svivian** [comment]
:+1:

**Comment by fredck** [comment]
+1

**Comment by Petoj87** [comment]
Any news on this?

**Comment by mlewand** [comment]
Lately we've been really, really busy. However we finished our current pending task and now can focus on other things including this issue. We should be able to push it at the very beginning of a new year. We'll keep this ticket updated!

**Comment by f1ames** [comment]
Added PR (https://github.com/ckeditor/ckeditor-releases/pull/44) with package.json. Probably should be merged during next release?

**Comment by f1ames** [comment]
As @Reinmar suggested the default preset for npm should be standard-all. It is going to be published under name `ckeditor` and so it will be possible to install like:

    npm install ckeditor
    npm install ckeditor@4.5.7
    npm install ckeditor@latest

As for now this one preset should be sufficent. But what if somebody would like to have other presets install via npm?

### Instal directly from github

Since from the next release `package.json` will be available in all new branches (tags also) it will be possible to install directly from github:

    npm install git+git@github.com:ckeditor/ckeditor-releases.git#basic/4.5.7
    npm install git+git@github.com:ckeditor/ckeditor-releases.git#standard/4.5.7
    npm install git+git@github.com:ckeditor/ckeditor-releases.git#full/4.5.7
    npm install git+git@github.com:ckeditor/ckeditor-releases.git#4.5.7
    
It is not best solution but worth noticing that it can be done this way.

---
## Add other presets to npm repository

If we are going to consider adding other presets to npm in future, it can be done at least in two different ways.

#### 1. Add presets as separate packages to npm
So there will be 4 different packages, e.g. _ckeditor, ckeditor-basic, ckeditor-standard, ckeditor-full_. From cli point of view it could be pretty convient to use because we can do:

    npm install ckeditor-basic
    npm install ckeditor-standard@4.5.7
    npm install ckeditor-full@latest

Also easy when using `npm publish`, no need to any workorounds or hacking. So it is the proper way to use npm. 

The problem with this solution is that there will be 4 ckeditor packages in npm repo which can be very confusing. Basically it sholud be one package because this is the same project/package only in different versions. This I think pretty much disqualifies this solution.

#### 2. Add presets as tags
This is more hacky way similar to one used for bower. The presets (_basic, standard, full_) could be published to npm with additional tags. So e.g. full package could be published like:

    npm publish --tag full-4.5.7
    
and then installed like:

    npm install ckeditor@full-4.5.7
    
It is also possible to add `latest` and package without version number:

    npm publish --tag full
    npm publish --tag full-latest
    
so it can be installed like:

    npm install ckeditor@full
    npm install ckeditor@full-latest
    
There are two problems with this solution, to publish all tags for single version it requires to use `npm publish` command ten times (once for ckeditor and 3 times for every preset: --tag preset, --tag preset-latest, -- tag preset-version) comparing to 4 times in previous solution.

The second problem is that one package version cannot be published more than once even with different tags, so e.g. considering full preset:
    
    npm publish --tag full
    npm publish --tag full-4.5.7
    npm publish --tag full-latest
    
for every publish operation, `package.json` should hav different version e.g.

    "version": "4.5.7-full"
    "version": "4.5.7-full-withversion"
    "version": "4.5.7-full-latest"
    
So it is possible but quite tricky/messy way to do this. And using it via cli may seem somehow inconsistent.

**Comment by awHamer** [comment]
+1

**Comment by ksdev-pl** [comment]
+1. Please add installation via npm

**Comment by frontyard** [comment]
+1. Is there a bounty for this?

**Comment by belfz** [comment]
+1. Is this scheduled for next few days?

**Comment by mlewand** [comment]
Thanks for the feedback, we're looking to review it next week. As it gets reviewed we'll push it very shortly.

**Comment by mlewand** [comment]
Ok, package file looks fine. We might also publish ckeditor-dev verison on npm, but it's a separate task.

**Comment by sdebacker** [comment]
Thank you!

**Comment by mlewand** [comment]
You can download it using `npm install ckeditor` so feel free to already use it. However we'll officially announce it once we have all the docs changes (ckeditor/ckeditor-docs#64) needed for it. :)
