### ISSUE TITLE
Kama skin missing?

### ISSUE THREAD

**Issue by mikemix** [ckeditor/ckeditor-releases#39]
Why does **full/4.5.3** branch include only moono skin without the kama skin, while **standard/4.5.3** does include both skins?

**Comment by Reinmar** [comment]
[standard/4.5.3](https://github.com/ckeditor/ckeditor-releases/tree/standard/4.5.3/skins) includes only the moono skin. The [4.5.3](https://github.com/ckeditor/ckeditor-releases/tree/4.5.3/skins) tag contains both skins because this is the standard-all preset (so all official plugins and skins are available). There are no full-all and basic-all presets, but I don't think it makes sense to add another two builds.
