### ISSUE TITLE
Can't install alternate distribution releases with composer

### ISSUE THREAD

**Issue by rdoursenaud** [ckeditor/ckeditor-releases#41]
Following the docs at http://ckeditor.com/blog/CKEditor-Supports-Bower-and-Composer, I tried the following code:

``` json
"require": {
    "ckeditor/ckeditor": "full/4.3.3",
}
```

Unfortunately composer fails with the following message:

```
[UnexpectedValueException]                                                            
Could not parse version constraint full/4.3.3: Invalid version string "full/4.3.3"  
```

On the other hand branches seem to work OK. Unfortunately, I work with a very picky project manager that wants all dependencies to be pinned versions.

Is there any workarounds?

**Comment by schmunk42** [comment]
That does not work in general with composer libraries. You simply do not see the versions unless you're on stability dev.

**Comment by schmunk42** [comment]
This is what worked for us: `"ckeditor/ckeditor": "~4.7.0+full"`

**Comment by rdoursenaud** [comment]
Thanks @schmunk42 for your insights.
Your latest suggestion pins the release but not the specific version.
I worked around it by adding the tag.
It's not very legible but does the trick for now.

The documentation still needs updating though…

**Comment by mlewand** [comment]
It looks that Comopser is simply not handling tags that way, since branches are working correctly. You can see [Fetching a Particular Build Preset](http://docs.ckeditor.com/#!/guide/dev_package_managers-section-fetching-a-particular-build-preset) section in our docs to find pretty much what @schmunk42 has suggested, so the docs are fine here.

As for workaround, since Composer doesn't play well with tags that contain backslash, you could simply pin the requirement to a given hash.

> To my understanding, using a / in the version tag is not covered by semver. Build metadata should be annotated with a + sign, see http://semver.org/#spec-item-10

Yes, these branches do not follow SemVer - we simply added them to allow devs to fetch a particular build.

**Comment by rdoursenaud** [comment]
@mlewand Thanks for your comment.
The docs are indeed fine but the blog I linked in my first message is not.
Unfortunately it's the first Google result for "ckeditor composer" hence my mixup.
Sorry for the confusion.

**Comment by schmunk42** [comment]
I haven't really tested it, but would you consider an additional tag like `4.7.0+full` if it would work fine?

**Comment by schmunk42** [comment]
The problem with composer and multiple distributions is, because of the fact that ckeditor is often included as a dependency, that you can not specify a version constraint like `^4.2.1`.

If you wanna include a full version, you have to "patch" your *root* `composer.json` pointing to a specific branch or version, which makes package management with dependency resolution useless in this setup.

Would be really nice, if you could provide a solution for this.

**Comment by mlewand** [comment]
And how would Composer resolve anything like `^4.7.0+full`? I'm afraid that it will simply skip meta info, and will just use any other preset. That's a no-go for us if it would replace `4.x.x+basic` with a `4.x.x+full` or the other way around during the update.

**Comment by schmunk42** [comment]
Tried it with a fork and it does not work :(

See my issue in composer/composer...

**Comment by schmunk42** [comment]
Any chance to make this happen?

> It should be released as 3 different packages. E.g. ckeditor/ckeditor (standard), ckeditor/ckeditor-basic, ckeditor/ckeditor-full

https://github.com/composer/composer/issues/6489#issuecomment-309031176

**Comment by mlewand** [comment]
It is a possibility, I created #69 for this, however it's not a hi priority for us ATM as it will require a bit of work to make it happen (and maintain backward compat).
