### ISSUE TITLE
Downloading full version

### ISSUE THREAD

**Issue by yusupprog** [ckeditor/ckeditor-releases#73]
Please do not report issues in CKEditor. The correct location of CKEditor issue tracker is: http://dev.ckeditor.com/

`npm install ckeditor@full/4.7.3`

```npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/full/4.7.3.git```

Am I doing something wrong?

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

---

Please refer to our documentation on [Installing CKEditor with Package Managers](https://docs.ckeditor.com/#!/guide/dev_package_managers), and if you would like to install `ckeditor-releases` package directly from Github use:

```
npm install git+https://github.com/ckeditor/ckeditor-releases.git#full/4.7.3
```
