### ISSUE TITLE
CKEditor 4 td input error on Korean.

### ISSUE THREAD

**Issue by jangsunjin** [ckeditor/ckeditor-releases#78]
Dear, 

I found a problem with Google Chrome web browser when I typed Korean in the table of CKEditor 4.
That is, a bug occurs when CKEditor creates a table and enters Korean in td.

Please refer to the image I uploaded.
![image](https://user-images.githubusercontent.com/1546045/37446026-5a726710-285e-11e8-9e3e-28c427cd1dae.png)

**한글** is entered in the column, but **ㅎㅏㄴ** is entered.
Korean characters consist of 2byte, causing problems in input process.

I used CKEditor 4 on Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)
This happened after Google Chrome was updated today.

So, Please check this rapidly.
Because, I think, this issue is happening to all Asian users.

Thanks for all.

**Comment by msamsel** [comment]
Hello

thank you for your bug report, but this repository is not appropriate for such bug reports.
I've create this same bug in proper place here: https://github.com/ckeditor/ckeditor-dev/issues/1848, and that's why I close the issue here.
If you wish to monitor your bug report please watch mentioned issue.
