### ISSUE TITLE
After copy & paste ckeditor data, Custom plugin data is not rendered in ckeditor 

### ISSUE THREAD

**Issue by GnanaprakashChandiran** [ckeditor/ckeditor-releases#79]
Steps to reproduce:
1. load same sites in multiple tabs(tab1, tab2).
2. i have created custom plugins.
3. Insert custom plugin data into ckeditor(tab1). 
4. Copy tab1 ckeditior data and paste data into tab2 ckeditor.
Now, custom plugins data is not rendered in tab2 ckeditor

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.
